### PR TITLE
Replace 'non-confidential' with RFC DL.

### PR DESCRIPTION
**Pull request by jbspeakr**
This addresses #537.

### CODE REVIEW

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Stackenblochen! :smile:

**Comment by jbspeakr** [comment]
@hjacobs actually not – using established terms in your shared domain language is especially important when people from different backgrounds come together or the topic itself is kinda hard to grasp for a lot of people... in the case of OAuth, both is pretty much given.

**Comment by jbspeakr** [comment]
👍

**Pull request merged**
